### ISSUE TITLE
Parametrise alfresco installer URL

### ISSUE THREAD

**Issue by pzrinscak** [gui81/docker-alfresco#10]
You could paramterise alfresco installer URL with --build-arg flag and ARG dockerfile instruction. That way you could build and tag images for different alfresco versions without changes in the source code.
Just an idea.

**Comment by gui81** [comment]
Could.  I'll consider it, but I think I would get a lot more issues if a newer version breaks something in one of the configs.  For now I will stick with explicitly defining the version so that I can double check that things still work with each new version.
