### ISSUE TITLE
Set memory size

### ISSUE THREAD

**Issue by moroz-off** [gui81/docker-alfresco#13]
Hello!

As you can skip this test? Docker is running in a virtual machine.

`1.95 GB of RAM is not enough to run Alfresco for test or production purposes. Alfresco might not work correctly and if it does, will not perform well. Upgrade the server to have at least 2.0 GB of RAM, and optimally 4.0 GB of RAM.
ERROR: Service 'alfresco' failed to build: The command '/bin/sh -c /tmp/install_alfresco.sh &> /dev/null &&     rm -f /tmp/install_alfresco.sh &> /dev/null' returned a non-zero code: 1`

**Comment by gui81** [comment]
Yes, Alfresco has minimum requirements for memory as well as other resources.  Consult the Alfresco documentation if you need to know what they are.  I don't see what you are asking here, so closing.
