### ISSUE TITLE
Document preview

### ISSUE THREAD

**Issue by jmcarranza** [gui81/docker-alfresco#14]
I have tried a thousand ways without luck. We did not make document visualization work.
We have seen that a library is missing, we have installed it, we get libreoffice started but the problem persists. Does anyone else have this problem?

**Comment by gui81** [comment]
I have updated the CentOS pkgs used and also updated to the latest version of Alfresco, 201707.

**Comment by gui81** [comment]
closing unless more details can be provided proving this is an error with the image.
