### ISSUE TITLE
When mounting data volumes (-v) keystore and PostgreSQL data missing

### ISSUE THREAD

**Issue by peterschen** [gui81/docker-alfresco#2]
When using the -v switch for the docker run command on a freshly pulled image Alfresco is not booting up properly as required data (such as the PostgreSQL data and keystore files are missing). There should be some kind of initialization which provides these data in case they are not existent.

**Comment by NahumLitvin** [comment]
Im having the same problem.
Boot2Docker on windows 7

**Comment by rsippl** [comment]
This should be fixed in my fork, via the new var CONTENT_STORE. Make sure you read the Readme there.

**Comment by mathiasconradt** [comment]
I am having the same problem, the error log (http://pastebin.com/W27Fy5TN) shows:
`Context initialization failed
org.alfresco.error.AlfrescoRuntimeException: 01230001 Keystores are invalid`

**Comment by rsippl** [comment]
@mathiasconradt give this one a try: https://hub.docker.com/r/rsippl/alfresco

**Comment by mathiasconradt** [comment]
@rsippl I tried your project, but as soon as I use CONTENT_STORE parameter, I get problems with the startup.

`docker run --name='alfresco' -it --rm -p 8080:8080 -v /Users/mln/tmp/alf_data:/alfresco/alf_data -e CONTENT_STORE=/alfresco/alf_data rsippl/alfresco`

Error log (http://pastebin.com/Y9dK77TP):

`Could not instantiate bean class [org.alfresco.repo.domain.schema.DataSourceCheck]: Constructor threw exception; nested exception is java.lang.RuntimeException: Database connection failed: Cannot create PoolableConnectionFactory (Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)`

(I would assume that the CONTENT_STORE paramter is independent from the DB_KIND (regardless whether I use postgresql or mysql?)

It works fine, when I start with just:

`docker run --name='alfresco' -it --rm -p 8080:8080 rsippl/alfresco`

**Comment by bkoz** [comment]
I was able to configure persistence by setting CONTENT_STORE=/content (i.e. something other than /alfresco/alf_data) using the rsippl/alfresco image.

**Comment by rsippl** [comment]
@mathiasconradt make sure your content store folder is empty on first run. Best if you set CONTENT_STORE to something other than /alfresco/alf_data, as bkoz suggested (I'll look into why this is happening sometime soon).

**Comment by mathiasconradt** [comment]
@rsippl @bkoz Thanks, using a different path works.

**Comment by bkoz** [comment]
Great news Mathias. BTW, I have the app running on OpenShift using 2 Kubernetes pods. In order to do so, I had to relax my security settings because the alfresco container likes to run with root-like privileges. @rsippl, any plans to change this?

bkoz

**Comment by rsippl** [comment]
@bkoz please open a new issue for this here: https://github.com/rsippl/docker-alfresco/issues

**Comment by gui81** [comment]
Try the latest version, it should work for you now.  I've also updated to the latest 201604 community installer.
