### ISSUE TITLE
Docker Not Building

### ISSUE THREAD

**Issue by laayis** [gui81/docker-alfresco#23]
Hi am new to docker. When i try to build an image, i keep getting the below error. Please assist.

ERROR: Service 'alfresco' failed to build: The command '/bin/sh -c /tmp/install_alfresco.sh &&     rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 2

**Comment by fracat71** [comment]
I receive : 

"The command '/bin/sh -c /tmp/install_alfresco.sh &&     rm -rf /tmp/* /var/tmp/*' returned a non-zero code: 127". 

Have you resolved?

**Comment by laayis** [comment]
Not yet resolved.

**Comment by kphareesh1994** [comment]
Same issue i am  also facing can any one help me in resolving the issue
