### ISSUE TITLE
Disable CSRF policy

### ISSUE THREAD

**Issue by DamienMure** [gui81/docker-alfresco#3]
Hi.
I need to disable CSRF policy in /alfresco/tomcat/shared/classes/alfresco/web-extension/share-config-custom.xml file.
It is not possible to do that with your current container.
If you don't mind, I plane to fork your project, make some change and perform a nice pull request...
(https://github.com/ATIH/docker-alfresco)

Regards.

**Comment by gui81** [comment]
Merged.  Thanks for the changes.

**Comment by gui81** [comment]
After merging, I realized that my SHARE_PORT and ALFRESCO_PORT were being set to null, so I had to revert this portion of the merge.  Perhaps this worked for you if you had these values set with an environment variable, but were not working if these values were not set.

**Comment by DamienMure** [comment]
Sorry for this mistake. I thought I checked that.
I'll correct this ASAP.
